import { ServiceStrategy } from "@/services/service-strategy";

export default class ExecutionAgent {
  service: ServiceStrategy;

  constructor(service: ServiceStrategy) {
    this.service = service;
  }

  /**
   * Executes a task based on the given objective and previous context.
   * @param objective The objective or goal for the AI to perform the task.
   * @param task The task to be executed by the AI.
   * @returns The response generated by the AI for the given task.
   */
  public async executeTask(objective: string, task: string): Promise<string> {
    const context = await this.getContext(
      (query = objective),
      (top_results_num = 5)
    );
    const prompt = PromptGenerator.generatePrioritizationAgentPrompt(
      objective,
      task,
      context
    );
    return this.service.callService(prompt, 2000);
  }
}
